# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Problyzer-v.simplified.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2147, 1540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("OB_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.Label_status = QtWidgets.QLabel(self.centralwidget)
        self.Label_status.setText("")
        self.Label_status.setObjectName("Label_status")
        self.horizontalLayout_3.addWidget(self.Label_status)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, 20, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.Line_Conc = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Conc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_Conc.sizePolicy().hasHeightForWidth())
        self.Line_Conc.setSizePolicy(sizePolicy)
        self.Line_Conc.setMinimumSize(QtCore.QSize(0, 0))
        self.Line_Conc.setMaximumSize(QtCore.QSize(130, 16777215))
        self.Line_Conc.setObjectName("Line_Conc")
        self.horizontalLayout_4.addWidget(self.Line_Conc)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(30, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.Combo_ChooseProgram = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Combo_ChooseProgram.sizePolicy().hasHeightForWidth())
        self.Combo_ChooseProgram.setSizePolicy(sizePolicy)
        self.Combo_ChooseProgram.setMinimumSize(QtCore.QSize(0, 0))
        self.Combo_ChooseProgram.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Combo_ChooseProgram.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Combo_ChooseProgram.setFont(font)
        self.Combo_ChooseProgram.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Combo_ChooseProgram.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.Combo_ChooseProgram.setObjectName("Combo_ChooseProgram")
        self.Combo_ChooseProgram.addItem("")
        self.Combo_ChooseProgram.addItem("")
        self.Combo_ChooseProgram.addItem("")
        self.Combo_ChooseProgram.addItem("")
        self.horizontalLayout_4.addWidget(self.Combo_ChooseProgram, 0, QtCore.Qt.AlignHCenter)
        self.Button_Run = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Run.setEnabled(False)
        self.Button_Run.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Button_Run.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_Run.setAutoFillBackground(False)
        self.Button_Run.setCheckable(True)
        self.Button_Run.setObjectName("Button_Run")
        self.horizontalLayout_4.addWidget(self.Button_Run)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Button_ShowImage = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ShowImage.setEnabled(False)
        self.Button_ShowImage.setObjectName("Button_ShowImage")
        self.horizontalLayout_4.addWidget(self.Button_ShowImage)
        self.Combo_ImageType = QtWidgets.QComboBox(self.centralwidget)
        self.Combo_ImageType.setEnabled(False)
        self.Combo_ImageType.setMinimumSize(QtCore.QSize(0, 0))
        self.Combo_ImageType.setObjectName("Combo_ImageType")
        self.Combo_ImageType.addItem("")
        self.Combo_ImageType.addItem("")
        self.horizontalLayout_4.addWidget(self.Combo_ImageType, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 50, 0)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Line_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_filename.setMinimumSize(QtCore.QSize(0, 50))
        self.Line_filename.setObjectName("Line_filename")
        self.horizontalLayout.addWidget(self.Line_filename)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.horizontalLayout.addItem(spacerItem2)
        self.Button_Upload = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Upload.setObjectName("Button_Upload")
        self.horizontalLayout.addWidget(self.Button_Upload)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2099, 1175))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 1, 4, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 1, 5, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 1, 9, 1, 1)
        self.Slider_ShapeStringency = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.Slider_ShapeStringency.setEnabled(False)
        self.Slider_ShapeStringency.setMaximum(100)
        self.Slider_ShapeStringency.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_ShapeStringency.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_ShapeStringency.setTickInterval(5)
        self.Slider_ShapeStringency.setObjectName("Slider_ShapeStringency")
        self.gridLayout_2.addWidget(self.Slider_ShapeStringency, 2, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 9, 1, 1)
        self.Slider_Dilate = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.Slider_Dilate.setEnabled(False)
        self.Slider_Dilate.setMinimumSize(QtCore.QSize(0, 0))
        self.Slider_Dilate.setMaximumSize(QtCore.QSize(1677, 1677))
        self.Slider_Dilate.setMinimum(1)
        self.Slider_Dilate.setMaximum(7)
        self.Slider_Dilate.setSingleStep(2)
        self.Slider_Dilate.setPageStep(10)
        self.Slider_Dilate.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Dilate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_Dilate.setTickInterval(1)
        self.Slider_Dilate.setObjectName("Slider_Dilate")
        self.gridLayout_2.addWidget(self.Slider_Dilate, 0, 5, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMaximumSize(QtCore.QSize(200, 50))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.Check_ShapeStringency = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_ShapeStringency.setObjectName("Check_ShapeStringency")
        self.gridLayout_2.addWidget(self.Check_ShapeStringency, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 9, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.Check_SpotStringency = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_SpotStringency.setObjectName("Check_SpotStringency")
        self.gridLayout_2.addWidget(self.Check_SpotStringency, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 1, 3, 1, 1)
        self.Slider_SpotStringency = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.Slider_SpotStringency.setEnabled(False)
        self.Slider_SpotStringency.setMinimumSize(QtCore.QSize(0, 0))
        self.Slider_SpotStringency.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Slider_SpotStringency.setMinimum(-1000)
        self.Slider_SpotStringency.setMaximum(200)
        self.Slider_SpotStringency.setSingleStep(1)
        self.Slider_SpotStringency.setProperty("value", 200)
        self.Slider_SpotStringency.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_SpotStringency.setInvertedAppearance(False)
        self.Slider_SpotStringency.setInvertedControls(False)
        self.Slider_SpotStringency.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_SpotStringency.setTickInterval(50)
        self.Slider_SpotStringency.setObjectName("Slider_SpotStringency")
        self.gridLayout_2.addWidget(self.Slider_SpotStringency, 2, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 1, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 1, 1, 1, 1)
        self.Slider_Sigma = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.Slider_Sigma.setEnabled(False)
        self.Slider_Sigma.setMinimumSize(QtCore.QSize(0, 0))
        self.Slider_Sigma.setMaximumSize(QtCore.QSize(1677, 50))
        self.Slider_Sigma.setMinimum(0)
        self.Slider_Sigma.setMaximum(100)
        self.Slider_Sigma.setPageStep(10)
        self.Slider_Sigma.setProperty("value", 2)
        self.Slider_Sigma.setSliderPosition(2)
        self.Slider_Sigma.setTracking(True)
        self.Slider_Sigma.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Sigma.setInvertedAppearance(False)
        self.Slider_Sigma.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_Sigma.setTickInterval(5)
        self.Slider_Sigma.setObjectName("Slider_Sigma")
        self.gridLayout_2.addWidget(self.Slider_Sigma, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 1)
        self.Slider_Blur = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.Slider_Blur.setEnabled(False)
        self.Slider_Blur.setMaximum(100)
        self.Slider_Blur.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Blur.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_Blur.setTickInterval(5)
        self.Slider_Blur.setObjectName("Slider_Blur")
        self.gridLayout_2.addWidget(self.Slider_Blur, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ClusterMap = ClusterMap(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClusterMap.sizePolicy().hasHeightForWidth())
        self.ClusterMap.setSizePolicy(sizePolicy)
        self.ClusterMap.setMinimumSize(QtCore.QSize(0, 0))
        self.ClusterMap.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        self.ClusterMap.setFont(font)
        self.ClusterMap.setToolTipDuration(-1)
        self.ClusterMap.setWhatsThis("")
        self.ClusterMap.setObjectName("ClusterMap")
        self.verticalLayout_2.addWidget(self.ClusterMap)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14, 0, QtCore.Qt.AlignLeft)
        self.Label_SpotNr = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_SpotNr.setMinimumSize(QtCore.QSize(100, 0))
        self.Label_SpotNr.setText("")
        self.Label_SpotNr.setObjectName("Label_SpotNr")
        self.horizontalLayout_8.addWidget(self.Label_SpotNr, 0, QtCore.Qt.AlignLeft)
        self.Check_SizeThres = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_SizeThres.setText("")
        self.Check_SizeThres.setObjectName("Check_SizeThres")
        self.horizontalLayout_8.addWidget(self.Check_SizeThres)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.Slider_SizeThres = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.Slider_SizeThres.setEnabled(False)
        self.Slider_SizeThres.setMaximum(255)
        self.Slider_SizeThres.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_SizeThres.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_SizeThres.setTickInterval(20)
        self.Slider_SizeThres.setObjectName("Slider_SizeThres")
        self.horizontalLayout_8.addWidget(self.Slider_SizeThres)
        self.Button_ImgViewer = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.Button_ImgViewer.setObjectName("Button_ImgViewer")
        self.horizontalLayout_8.addWidget(self.Button_ImgViewer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.Check_NoisyMode = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_NoisyMode.setEnabled(False)
        self.Check_NoisyMode.setMinimumSize(QtCore.QSize(0, 0))
        self.Check_NoisyMode.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.Check_NoisyMode.setObjectName("Check_NoisyMode")
        self.verticalLayout.addWidget(self.Check_NoisyMode, 0, QtCore.Qt.AlignHCenter)
        self.Check_SingleColor = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_SingleColor.setEnabled(False)
        self.Check_SingleColor.setMinimumSize(QtCore.QSize(0, 0))
        self.Check_SingleColor.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Check_SingleColor.setChecked(True)
        self.Check_SingleColor.setObjectName("Check_SingleColor")
        self.verticalLayout.addWidget(self.Check_SingleColor, 0, QtCore.Qt.AlignHCenter)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Slider_LowThres = QtWidgets.QSlider(self.frame)
        self.Slider_LowThres.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_LowThres.sizePolicy().hasHeightForWidth())
        self.Slider_LowThres.setSizePolicy(sizePolicy)
        self.Slider_LowThres.setMinimumSize(QtCore.QSize(200, 0))
        self.Slider_LowThres.setMaximumSize(QtCore.QSize(350, 16777215))
        self.Slider_LowThres.setMaximum(127)
        self.Slider_LowThres.setSingleStep(1)
        self.Slider_LowThres.setPageStep(10)
        self.Slider_LowThres.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_LowThres.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_LowThres.setTickInterval(5)
        self.Slider_LowThres.setObjectName("Slider_LowThres")
        self.gridLayout_4.addWidget(self.Slider_LowThres, 0, 1, 1, 1)
        self.Slider_HighThres = QtWidgets.QSlider(self.frame)
        self.Slider_HighThres.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_HighThres.sizePolicy().hasHeightForWidth())
        self.Slider_HighThres.setSizePolicy(sizePolicy)
        self.Slider_HighThres.setMinimumSize(QtCore.QSize(200, 0))
        self.Slider_HighThres.setMaximumSize(QtCore.QSize(350, 16777215))
        self.Slider_HighThres.setMinimum(127)
        self.Slider_HighThres.setMaximum(255)
        self.Slider_HighThres.setProperty("value", 255)
        self.Slider_HighThres.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_HighThres.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_HighThres.setTickInterval(5)
        self.Slider_HighThres.setObjectName("Slider_HighThres")
        self.gridLayout_4.addWidget(self.Slider_HighThres, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.Button_DAPI = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Button_DAPI.setEnabled(False)
        self.Button_DAPI.setMinimumSize(QtCore.QSize(0, 0))
        self.Button_DAPI.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Button_DAPI.setToolTip("")
        self.Button_DAPI.setToolTipDuration(3)
        self.Button_DAPI.setWhatsThis("")
        self.Button_DAPI.setObjectName("Button_DAPI")
        self.verticalLayout.addWidget(self.Button_DAPI, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Label_DAPI = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_DAPI.setMinimumSize(QtCore.QSize(0, 0))
        self.Label_DAPI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Label_DAPI.setText("")
        self.Label_DAPI.setObjectName("Label_DAPI")
        self.verticalLayout.addWidget(self.Label_DAPI, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Label_TissueSNR = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_TissueSNR.setMinimumSize(QtCore.QSize(0, 0))
        self.Label_TissueSNR.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Label_TissueSNR.setText("")
        self.Label_TissueSNR.setObjectName("Label_TissueSNR")
        self.verticalLayout.addWidget(self.Label_TissueSNR, 0, QtCore.Qt.AlignHCenter)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23, 0, QtCore.Qt.AlignHCenter)
        self.Button_SNR = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Button_SNR.setEnabled(False)
        self.Button_SNR.setMinimumSize(QtCore.QSize(0, 0))
        self.Button_SNR.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Button_SNR.setObjectName("Button_SNR")
        self.verticalLayout.addWidget(self.Button_SNR, 0, QtCore.Qt.AlignHCenter)
        self.Check_MaximaNoisyMode = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_MaximaNoisyMode.setEnabled(False)
        self.Check_MaximaNoisyMode.setObjectName("Check_MaximaNoisyMode")
        self.verticalLayout.addWidget(self.Check_MaximaNoisyMode, 0, QtCore.Qt.AlignHCenter)
        self.Check_TissueMaxima = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Check_TissueMaxima.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Check_TissueMaxima.sizePolicy().hasHeightForWidth())
        self.Check_TissueMaxima.setSizePolicy(sizePolicy)
        self.Check_TissueMaxima.setMinimumSize(QtCore.QSize(0, 0))
        self.Check_TissueMaxima.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.Check_TissueMaxima.setChecked(True)
        self.Check_TissueMaxima.setObjectName("Check_TissueMaxima")
        self.verticalLayout.addWidget(self.Check_TissueMaxima, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.Label_SNR = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_SNR.setMinimumSize(QtCore.QSize(100, 0))
        self.Label_SNR.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Label_SNR.setText("")
        self.Label_SNR.setObjectName("Label_SNR")
        self.verticalLayout.addWidget(self.Label_SNR, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Label_CellSNR = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_CellSNR.setMinimumSize(QtCore.QSize(100, 0))
        self.Label_CellSNR.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Label_CellSNR.setText("")
        self.Label_CellSNR.setObjectName("Label_CellSNR")
        self.verticalLayout.addWidget(self.Label_CellSNR, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.Text_Log = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_Log.sizePolicy().hasHeightForWidth())
        self.Text_Log.setSizePolicy(sizePolicy)
        self.Text_Log.setMinimumSize(QtCore.QSize(0, 0))
        self.Text_Log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Text_Log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Text_Log.setReadOnly(True)
        self.Text_Log.setOverwriteMode(False)
        self.Text_Log.setObjectName("Text_Log")
        self.verticalLayout_4.addWidget(self.Text_Log, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.Line_SaveName = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_SaveName.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Line_SaveName.setObjectName("Line_SaveName")
        self.horizontalLayout_5.addWidget(self.Line_SaveName)
        self.Button_SaveResults = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SaveResults.setEnabled(False)
        self.Button_SaveResults.setMaximumSize(QtCore.QSize(500, 16777215))
        self.Button_SaveResults.setObjectName("Button_SaveResults")
        self.horizontalLayout_5.addWidget(self.Button_SaveResults, 0, QtCore.Qt.AlignLeft)
        self.Button_SaveMaximas = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SaveMaximas.setEnabled(False)
        self.Button_SaveMaximas.setObjectName("Button_SaveMaximas")
        self.horizontalLayout_5.addWidget(self.Button_SaveMaximas)
        self.Label_Exported = QtWidgets.QLabel(self.centralwidget)
        self.Label_Exported.setMinimumSize(QtCore.QSize(0, 0))
        self.Label_Exported.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Label_Exported.setText("")
        self.Label_Exported.setObjectName("Label_Exported")
        self.horizontalLayout_5.addWidget(self.Label_Exported, 0, QtCore.Qt.AlignLeft)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Button_Upload.clicked.connect(self.Line_filename.clear)
        self.Check_SpotStringency.clicked['bool'].connect(self.Slider_SpotStringency.setEnabled)
        self.Check_SizeThres.clicked['bool'].connect(self.Slider_SizeThres.setEnabled)
        self.Check_ShapeStringency.clicked['bool'].connect(self.label_21.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Status:"))
        self.label_3.setText(_translate("MainWindow", "Probe Concentration:"))
        self.Line_Conc.setToolTip(_translate("MainWindow", "Conc. of Seq 1, Conc. of Seq 2 ....Conc. of Seq n"))
        self.label_4.setText(_translate("MainWindow", "μM"))
        self.label.setText(_translate("MainWindow", "Program:"))
        self.Combo_ChooseProgram.setToolTip(_translate("MainWindow", "<html><head/><body><p>- <span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; color:#c7254e; background-color:#f9f2f4;\">RNAcofold</span> works much like RNAfold but uses two RNA sequences as input which are then allowed to form a dimer structure. </p><p>- <span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; color:#c7254e; background-color:#f9f2f4;\">RNAduplex</span> program is a fast alternative, that works by predicting only intermolecular base pairs. It’s almost as fast as simple sequence alignment, but much more accurate than a BLAST search.</p><p>- Since <span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; color:#c7254e; background-color:#f9f2f4;\">RNAduplex</span> forms only intermolecular pairs, it neglects the competition between intramolecular folding and hybridization. Thus, it is recommended to use <span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; color:#c7254e; background-color:#f9f2f4;\">RNAduplex</span> as a pre-ﬁlter and analyse good <span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; color:#c7254e; background-color:#f9f2f4;\">RNAduplex</span>hits additionally with <span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; color:#c7254e; background-color:#f9f2f4;\">RNAcofold or RNAup</span></p><p>&lt;Visit: <a href=\"https://www.tbi.univie.ac.at/RNA/tutorial/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.tbi.univie.ac.at/RNA/tutorial/</span></a> for more></p></body></html>"))
        self.Combo_ChooseProgram.setItemText(0, _translate("MainWindow", "RNAcoFold - MFE (no conc.)"))
        self.Combo_ChooseProgram.setItemText(1, _translate("MainWindow", "RNAcoFold - conc. dependent"))
        self.Combo_ChooseProgram.setItemText(2, _translate("MainWindow", "RNAduplex"))
        self.Combo_ChooseProgram.setItemText(3, _translate("MainWindow", "RNAup "))
        self.Button_Run.setText(_translate("MainWindow", "Run"))
        self.Button_ShowImage.setText(_translate("MainWindow", "Display Image"))
        self.Combo_ImageType.setItemText(0, _translate("MainWindow", "Tissue (DAPI/All)"))
        self.Combo_ImageType.setItemText(1, _translate("MainWindow", "Fluorescence (Signal)"))
        self.Button_Upload.setText(_translate("MainWindow", "Upload File"))
        self.label_21.setText(_translate("MainWindow", "Shape Stringency: "))
        self.label_6.setText(_translate("MainWindow", "Dilate: "))
        self.Check_ShapeStringency.setText(_translate("MainWindow", "Use: "))
        self.label_19.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">A local maximum M of height h is a local maximum for which there is at least one path joining M with a higher maximum on which the minimal value is f(M) - h (i.e. the values along the path are not decreasing by more than h with respect to the maximum’s value) and no path for which the minimal value is greater.</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Spot Stringency: "))
        self.Check_SpotStringency.setText(_translate("MainWindow", "Use: "))
        self.label_5.setText(_translate("MainWindow", "Sigma (Gaussian): "))
        self.label_20.setText(_translate("MainWindow", "Blurring Radius: "))
        self.label_14.setText(_translate("MainWindow", "Fluorescence Spots Count: "))
        self.label_15.setToolTip(_translate("MainWindow", "Cut-off size for small spots"))
        self.label_15.setText(_translate("MainWindow", "Spot-size Lower Limit (no. of pixels):"))
        self.Button_ImgViewer.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "BG Masking"))
        self.Check_NoisyMode.setToolTip(_translate("MainWindow", "Uses image mean intensity as threshold"))
        self.Check_NoisyMode.setText(_translate("MainWindow", "Noise Tolerant (BG)"))
        self.Check_SingleColor.setToolTip(_translate("MainWindow", "Display all spots at single intensity & color"))
        self.Check_SingleColor.setText(_translate("MainWindow", "Show as Single Color"))
        self.label_18.setText(_translate("MainWindow", "Threshold"))
        self.label_17.setText(_translate("MainWindow", "High: "))
        self.label_16.setText(_translate("MainWindow", "Low: "))
        self.label_12.setText(_translate("MainWindow", "Region Selection"))
        self.Button_DAPI.setText(_translate("MainWindow", "Set Colored Region /&\n"
"Calculate Mean Tissue BG"))
        self.label_11.setText(_translate("MainWindow", "Region\'s Mean Intensity:"))
        self.label_7.setText(_translate("MainWindow", "Region/All SNR Ratio:"))
        self.label_23.setText(_translate("MainWindow", "Maximas"))
        self.Button_SNR.setText(_translate("MainWindow", "Calculate Maximas\' SNR"))
        self.Check_MaximaNoisyMode.setText(_translate("MainWindow", "Noise Tolerant (Maxima)"))
        self.Check_TissueMaxima.setText(_translate("MainWindow", "Show In-bound Maximas Only"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Maximas/All SNR: </p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Maximas/Region SNR:</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Log:"))
        self.label_22.setText(_translate("MainWindow", "Name: "))
        self.Button_SaveResults.setText(_translate("MainWindow", "Save current results to directory"))
        self.Button_SaveMaximas.setText(_translate("MainWindow", "Save Maximas"))

from clustermap import ClusterMap

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

